### ISSUE TITLE
'bottomLayoutGuide' was deprecated in iOS 11.0

### ISSUE THREAD

**Issue by abeyuya** [exchangegroup/under-keyboard-ios#12]
Please consider submitting the following information (if relevant):

* Library setup method: CocoaPods
* Version of the library. Example: 10.0.0
* Xcode version. Example: 9.0
* OS version. Example: iOS 11

<img width="757" alt="2017-10-10 13 46 03" src="https://user-images.githubusercontent.com/1656414/31369781-b73ce410-adc1-11e7-96bc-e81dcacfa05b.png">

---

I have no idea to resolve this issue. sorry. 😣

**Comment by evgenyneu** [comment]
Hi, thanks for reporting. We need to fix this. For the time being, the workaround is to choose a deployment target to iOS 10 or earlier.

**Comment by evgenyneu** [comment]
Fixed in version 11, which introduced some [breaking changes](https://github.com/evgenyneu/UnderKeyboard#api-change-in-version-11).
