### ISSUE TITLE
Can't compile.

### ISSUE THREAD

**Issue by Ying1986** [exchangegroup/under-keyboard-ios#2]
I can't compile with this library  5.0+ (6.0) on Xcode 7.3.1.

What means **NotificationCenter**? **NS-**??

**Comment by evgenyneu** [comment]
Hi @Ying1986, thank you for your feedback. The "UnderKeyboard" library is written in Swift 3.0. If you need to use an older version of Swift you can find the setup instructions here:

https://github.com/marketplacer/UnderKeyboard/wiki/Legacy-Swift-versions

Let me know if it works for you.

**Comment by Ying1986** [comment]
Thank you.
