### ISSUE TITLE
default implementation for when you don't have a bottom constraint?

### ISSUE THREAD

**Issue by AndrewSB** [exchangegroup/under-keyboard-ios#3]
Really really cool library. I've been using https://github.com/hackiftekhar/IQKeyboardManager, but am trying `UnderKeyboard` for a new view, because I think it's a more deliberate way to handle the keyboard.

I was wondering what your thoughts were on having a default implementation for views without a bottom constraint? Where you'd simply find the selected `UITextField`'s `frame` in the current view, and move the view's y offset up by that amount?

If that sounds like a good idea to you, I'd love to give it a shot in a PR

**Comment by evgenyneu** [comment]
Hi @AndrewSB, that's a great idea. What do you suggest the API to be? Do you supply a view to it? Will it search for this view's child text fields and move up the one that is selected?

Thank you for your help.

**Comment by AndrewSB** [comment]
Something similar to this:
![](https://raw.githubusercontent.com/hackiftekhar/IQKeyboardManager/v3.3.0/Screenshot/IQKeyboardManagerCFD.jpg)

I think this functionality will have to be opt in - too expensive for people who aren't using it.

**Comment by AndrewSB** [comment]
Really complicated - I know. Im going to try to distill the simplest, no frills version of the above flow chart, and see if it works 😄

**Comment by evgenyneu** [comment]
Wow, this is an epic flowchart, thanks. I agree, it looks a bit complicated. The main point of UnderKeyboard library was to make it lightweight, with simple API and documentation, so people without masters degree in computer science could understand and use it in their apps :). In addition, I wanted its code to be as minimal as possible to reduce the maintenance costs, especially now when xcode betas come every week with changes in Swift. 

Do you think it is possible to implement this functionality with minimal efforts, simple API and documentation? I usually start implementing new feature with writing its README documentation. If we can start with the API it will most likely be simple and easy to use. 

Here is an example of an API. We call `setup` method and supply a view that contains text fields. When keyboard appears on screen the library shifts one current text field up. Is it what you had in mind?

```
@IBOutlet weak var viewWithTextFields: UIView!
let underKeyboardTextFieldObserver = UnderKeyboardTextFieldObserver()

override func viewDidLoad() {
  super.viewDidLoad()

  underKeyboardTextFieldObserver.setup(viewWithTextFields: viewWithTextFields,
    bottomLayoutGuide: bottomLayoutGuide)
}
```

**Comment by AndrewSB** [comment]
@evgenyneu I totally embrace that approach - simple and easy to reason about is something I'm looking for in my keyboard handling libraries :)

I think it may be possible to add a relatively simple default option, I handled the case I had in the app I was working on, so right now I don't have the burning need for a default implementation, but I do think a default implementation would be helpful in the future.

The documentation I was imagining for a default implementation would just be an additional static var on the `UnderKeyboard` class is:

``` swift
class UnderKeyboard {
    static var useDefaultImplementationIfNoneProvided: Bool = false
}
```

and the UnderKeyboard's default implementation would just check that flag before doing anything more complicated than whats already in the library?
I thought it best if the default behavior was opt in

**Comment by AndrewSB** [comment]
tracking on #4
