### ISSUE TITLE
Returning nil 

### ISSUE THREAD

**Issue by sagaya** [exchangegroup/under-keyboard-ios#5]
`underKeyboardLayoutConstraint.setup(bottomLayoutConstraint, view: view,bottomLayoutGuide: bottomLayoutGuide)` 

After doing this my app keeps crashing and returning nil value

**Comment by evgenyneu** [comment]
Hi @cosmo1234, thanks for reporting. Is there any error message?

**Comment by sagaya** [comment]
No no error just returning nil

**Comment by evgenyneu** [comment]
Sorry, where exactly do you see the nil value? As far as I remember, the `setup` method of the `UnderKeyboardLayoutConstraint` does not return anything.

**Comment by evgenyneu** [comment]
Closing the issue. Feel free to reopen if needed.
