### ISSUE TITLE
iOS 8 crashes

### ISSUE THREAD

**Issue by bull-xu** [exchangegroup/under-keyboard-ios#7]
When the viewToAnimate's window is nil, this line crashes:

![image](https://cloud.githubusercontent.com/assets/12520500/20698786/79582b6c-b657-11e6-9061-1950a21d1fd8.png)

Adding a check can fix this problem for iOS 8:

```
  func animateKeyboard(height: CGFloat) {
		if viewToAnimate?.window != nil {
			viewToAnimate?.layoutIfNeeded()
		}
  }

```

**Comment by evgenyneu** [comment]
Thank you very much @bull-xu-stride for this bug report. I have released a new version with your fix.
