### ISSUE TITLE
UnderKeyboardObserver not firing

### ISSUE THREAD

**Issue by GoldenJoe** [exchangegroup/under-keyboard-ios#8]
Attempting this on iOS 10. Neither of the observer blocks are called.

```
// Inside UIView.init

let keyboardObserver = UnderKeyboardObserver()
keyboardObserver.start()
        
// Called before the keyboard is animated
keyboardObserver.willAnimateKeyboard = { height in
    print("keyboard height: \(height)")
    self.bottom_constraint.constant = height
}
        
// Called inside the UIView.animateWithDuration animations block
keyboardObserver.animateKeyboard = { height in
    self.layoutIfNeeded()
}
```

**Comment by evgenyneu** [comment]
Thanks for reporting, @GoldenJoe. I created a demo app (see attached) and ran it in iOS 10 simulator. The closures are being called, so I could not reproduce your problem. Does the app work for you?

[UnderKeyboardDemo.zip](https://github.com/evgenyneu/UnderKeyboard/files/1077231/UnderKeyboardDemo.zip)

**Comment by GoldenJoe** [comment]
Ah, I see. The observer has to be a property. If it's just in the scope of init(:) it won't fire. Thanks.

**Comment by evgenyneu** [comment]
No worries. Yes, an `UnderKeyboardObserver` object needs to be persistent in order for it to catch those keyboard notifications. Good luck :).
